### ISSUE TITLE
Converter function accepts invalid input without throwing an error

### ISSUE THREAD

**Issue by hi2u** [HarasimowiczKamil/any-base#3]
I was doing some playing around with any-base on runkit: https://runkit.com/afx237/59d8a2de6cee03001248f85a

And noticed the following code appears to work without throwing an error, even though the input given to converterFunction() is invalid for the sourceAlphabet...

```js
var anyBase = require("any-base")

converterFunction = anyBase('01', '0123456789');

// Only 0 and 1 should be accepted as input?...
converterFunction('01thisshouldntwork'); // outputs "1"
```

**Comment by HarasimowiczKamil** [comment]
I added a thrown exception in the new version (1.1.0)
