### ISSUE TITLE
Drop 0 when converting from hex to bin

### ISSUE THREAD

**Issue by KristenGarnier** [HarasimowiczKamil/any-base#4]
Hello,

I used your module to convert from hex to bin, but faced a little problem : i was expecting the return string to represent the entire 16 bits, but only got 11.

In a nutshell, this is what i was trying to do : 
``` javascript
const anyBase = require('any-base'),
          hex2bin = anyBase(anyBase.HEX, anyBase.BIN);

console.log(hex2bin('0481'))
// outputs: 10010000001 | padded : 100 1000 0001
// wanted 0000010010000001 | padded : 0000 0100 1000 0001
```

This appends only when the bin is prefixed with 0's.
So theses numbers does not output the right format when they its the first character : 1, 2, 3, 4, 5, 6, 7
I fixed in my code, but that would be nice if the module could work with 0's prefixing.

Node_version: 9.2.0
OS: mac
module_version: 1.1.0
 
Have a nice day !

**Comment by HarasimowiczKamil** [comment]
The presentation method should be made outside this library.

By assumption, the library is to exchange a string of characters with one alphabet for the second alphabet. Of course, the exchange of the numerical system is exactly the same. Your base alphabet can be `0123456789abcdef` but can be` def1324956078bca` too. Your base alphabet can be `0123456789abcdef` but it can be` def1324956078bca` too. I can not distinguish between characters that represent zero. For example, I use it also to reduce the length of the ID.

**Comment by KristenGarnier** [comment]
Fair enough, i did not seen this that way !

Thank you for the explanation.
i'll close this issue, thank you for taking time to answer 👍 

Have a nice day !
