### ISSUE TITLE
leading zeroes lost when converting to anyBase.HEX

### ISSUE THREAD

**Issue by fredrivett** [HarasimowiczKamil/any-base#6]
When converting a HEX string to a new base, and then back to HEX, any leading zeroes on the original HEX string will be lost.

[This seems like it might be how HEX conversion normally works](https://stackoverflow.com/questions/15919979/convert-int-to-hex-with-leading-zeros), but obviously isn't desired when the process of converting a string one way, and then reversing the conversion later, should always return the same as the original string.

A fix here is to implement [`padStart`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart), which will add the leading zeroes back to the string, if the string isn't the length expected.

For us we were using a 32 character string, so using this code fixes this issue:
`const longId32Char = longId.padStart(32, "0");`

Raising as an issue here as this seems unexpected, so should ideally either be fixed or added to the repo. If this is agreed as a desirable fix, I can try and have a look to see if it's easy to fix myself, if helpful.

**Comment by HarasimowiczKamil** [comment]
This was reported #4 

Everyone uses this library for a different purpose in one leading zero is expected in another no. If you expect leading zeros in your case. Create your own class that will do it. It can use any-base for conversion and return in the format you need. 

For example, I used this library to minimize the length of id in links (DEC up to 64 characters), leading zeros would not be desirable in this case. Any-base only converts "numbers" to the view you should take care of yourself.
